// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.omo.repository;

import com.omo.repository.MenuItemRepository;
import org.springframework.stereotype.Repository;

privileged aspect MenuItemRepository_Roo_Mongo_Repository {
    
    declare @type: MenuItemRepository: @Repository;
    
}
